# name 必填
name = "Mysql2EsModelSocial"

# 内部用于保存位点、心跳等事项的库名，默认为 _gravity
internal-db-name = "_gravity"

#
# Input 插件的定义，此处定义使用 mysql
#
[input]
type = "mysql"
mode = "replication"
[input.config.source]
host = "127.0.0.1"
username = "root"
password = "JoLNCfUX0-7Xgre_W"
port = 33309
max-idle = 10
max-open = 10


[output]
type = "esmodel"

[output.config]
# 忽略 400（bad request）返回
# 当索引名不规范、解析错误时，Elasticsearch 会返回 400 错误
# 默认为 false，即遇到失败时会抛出异常，必须人工处理。设置为 true 时会忽略这些请求
ignore-bad-request = true

#
# 目标端 Elasticsearch 配置
# - 必选
#
[output.config.server]
# 连接的 Elasticsearch 地址，必选
urls = ["http://127.0.0.1:19200"]
# 是否进行节点嗅探，默认为 false
sniff = false
# 超时时间，默认为 1000ms
timeout = 2000
#失败重试次数，默认3次
retry-count=3

#
# 目标端鉴权配置
# - 可选
#
[output.config.server.auth]
username = ""
password = ""


### social 本地环境索引
[[output.config.routes]]
match-schema = "channel_data_local"
# 主表
match-table = "chd_import_data_info"
#索引名
index-name="import_data_info_local"
#类型名，es7该项无效
type-name="import_data"
#分片数
shards-num=3
#副本数
replicas-num=2
#包含的列，默认全部
include-column = []
#排除的列，默认没有
exclude-column = ["content"]

# 列名转义策略
[output.config.routes.convert-column]
import_data_id = "importDataId"
import_object_code = "importObjectCode"
encode_version = "encodeVersion"
department_id = "departmentId"
create_time = "createTime"
update_time = "updateTime"
del_flag = "delFlag"


[[output.config.routes.one-one]]
match-type = "JsonColumn"
match-schema = "channel_data_local"
match-table = "chd_import_data_info"
match-column = "content"
#外键列
fk-column = "id"
#包含的列，默认全部
include-column = []
#排除的列，默认没有
exclude-column = []
# 模式，1：子对象，2索引平铺
mode = 1
# 属性对象名，模式为1时有效
property-name = "detail"
# 属性前缀,模式为2时非必填
property-pre = ""

[output.config.routes.one-one.convert-column]

